# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Testing

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install Poetry and dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install poetry
    - name: Install Application
      run: |
        cd tools/utils
        python -m poetry install

    - name: Test with pytest
      run: |
        cd tools/utils
        python -m poetry run pytest
        python -m poetry run flake8 utils
    - name: Lint project with flake8 and mypy
      run: |
        cd tools/utils
        python -m poetry run flake8 utils
        python -m poetry run mypy utils
